

= Deploy the "System Under Test" example Hello World 

== Introduction

To execute e.g. a interoperability requirement test, a System Under Test is needed. +
The HelloWorld application is a simple Java application that can used as a System under Test. +
It represents a federation against which sample test of the testsuite TS_HelloWorld could be run.


 The testsuite TS_HelloWorld is integrated into the IVCT - container Image, 
 which you might have startet before.
 It is a good starting point to explore and understand the IVCT and test suites.
 Learn more about the TS_Helloworld at: https://github.com/IVCTool/IVCT_TestSuiteDevelopment



In the steps below we start the HelloWorld application with the previously described docker environment,
by using the Pitch RTI.



== Prerequisite

link:Deploy_the_IVCT_and_start.adoc[See "Deploy_the_IVCT_and_start.adoc" for explanations]

A Docker Engine and Docker Compose have been installed.

Pitch RTI is installed on this machine.

This repository is cloned to your Docker Host to get the example compositions.
 

== Adapt the HelloWorld environment settings

  deployment/ivct
  deployment/sut-hellowworld

Navigate to the directory `deployment/sut-helloworld`. +
Open the `.env` file in a text editor and verify the settings.
Different values need to be adapted to the system which is used:

Set the following to the installation directory of the local Pitch RTI on the host +
 `PITCH_RTI_HOME='C:\Program Files\prti1516e` +
 `PITCH_RTI_SETTINGS='C:\Users\*****\prti1516e`

The host where your docker Installation (with the later started IVCT Components) is at: +
 `DOCKERHOST=192.168.1.1`


Change the ip to the address where the Pitch CRC is running,
 the PORT may be fine. +
 `CRC_HOST=192.168.1.1` +
 `CRC_PORT=8989` +
 (if you want to connect with a remote pitch CRC this address differs from "DOCKERHOST".)

Verify if this variable for the pitch RTI is activated
 `SETTINGS_DESIGNATOR="crcAddress=${CRC_HOST}:${CRC_PORT}"`
   +
 
 
The settings in the docker-compose-sut-pi.yml file are fine to run the application.
  
'''

If you are experienced IVCT user you can change some variables your used  the docker-compose file. +

##ToDo: create one ore more new documents, which explains variables ivct/.env, sut-helloworld/.env, ivct/*.compose.yml, sut-hellorld/docker-compose-sut-.yml#


|===
| Environment Variable Name  | Description | Default if not set
| FEDERATE_NAME              | Name of the SUT. In the default parameter settings the federate name `A` is used. This setting must match the actual test case parameters.  | `A`
| POPULATION                 | Size of the starting population for the HelloWorld Country object.   | `10`
| CYCLES                     | Number if iterations before resigning the federate. The federate iterates every second, so this also determines the lifetime the helloworld federate.    | `1000000`
|===

'''


== Start the HelloWorld application

Start the application with
 
 docker-compose -f docker-compose-sut-pi.yml up
 

The SUT Docker container images will be pulled from the Docker Hub and the SUT will be deployed.
Afterwards it is connected to the specified RTI. (CRC_HOST )



== Further steps

=== Running HW_Testcases against the HelloWorld application

When the federate ist started, you can demonstrate the usage of IVCt with the example testsuite TS_HelloWorld.

link:Running_TS_Helloworld-tests_against_HelloWorld-application.adoc[]

