= Containerized IVCT

< WORK IN PROGRESS, SECTIONS will move to separate topic pages later >

https://docker.com[Docker] is an open source product that supports the creation, management and deployment of containers, and provides an easy way to deploy the IVCT on different platforms for different HLA-RTIs. All the IVCT components are available as container image.

NOTE: The reader is familiar with the Docker concepts and has the knowledge to install Docker on Windows or Linux.

NOTE: The reader is also familiar with HLA concepts and has the knowledge to install an HLA-RTI on Windows or Linux.

== Install and run the ICVT

Assuming Docker Engine and Docker Compose have been installed, the quickest way to deploy the IVCT is as follows:

. Determine the IVCT version that you want to deploy.

There is an IVCT version for each HLA-RTI variant. IVCT docker compositions are available for the following HLA-RTIs: `Pitch`, `VT MaK`, and `Portico`. In this example we use the Pitch RTI version of the IVCT. We also run the IVCT in `no host` mode, to be explained later.

. Copy the IVCT docker-compose file to your local environment.

Copy the file `docker-compose.yml` under the `ivct-pitch` directory to your local environment.

. Deploy the IVCT

Issue the command

 docker-compose up

The images will be pulled from the Docker Hub and the IVCT will be deployed by the Docker Engine.

. Navigate to the IVCT UI

From a webbrowser, navigate to the web page of the IVCT UI: `http://${DOCKERHOST}:8080`.  Here you should replace `${DOCKERHOST}` by the host name of the Docker Engine. Login as user `admin` with password `admin.`

You can explore the UI, but for running tests a System Under Test (SUT) is required, as well as a Pitch CRC.

== Testing the Hello World application
< TO BE ADDED >

== IVCT deployment options
< TO BE ELABORATED >

=== Host mode networking
This is the recommended deployment, as it allows the general use of TCP/IP, UDP/IP and Multicast communication with the SUT.

Note that Docker on Windows running Linux containers does not support host mode networking, only Docker on Linux does.

=== Non-host mode
This is only recommended when using reliable communication (i.e. TCP/IP). Depending on the RTI implementation, it may be possible to use UDP/IP in this mode. Multicast is not possible in this mode.

== IVCT RID file configuration
The IVCT uses a default (and RTI vendor specific) RID file when connecting to the RTI. This is sufficient in most cases.

The RID file for the MaK RTI has been set up to:
- use reliable communication to enable `nohost mode` networking
- let the RTI Exec perform license checks

To use an alternate RID, adapt the IVCT composition as follows:
< TO BE ADDED >

== RTI Settings Designator
< TO BE ADDED>

== IVCT Container images
=== Overview
=== Container image A
=== Container image B
=== Container image C
== Test Suite container images
=== creating a TS image
