= Testing the Hello World application

To execute a test, a System Under Test is needed. In the steps below we use the HelloWorld application with the Portico RTI as 
SUT.

The HelloWorld application is a simple Java application that can used as a System under Test. It is a good starting point to explore and understand the IVCT and test suites.

== Adapt the IVCT environment settings

Navigate to the directory `portico/bridge-network/sut-helloworld` and check the settings in the provided `.env` file.

In the `.env` file, there are several enviroment variables for the helloworld federate. The provided settings are already fine to run the application:

|===
| Environment Variable Name  | Description | Default if not set

| SETTINGS_DESIGNATOR        | Connection parmeter for the `RTIambassador.connect` method   |no default assumed, this variable must be set to the RTI service. A typical value would be `crcAddress=crc:8989`
| FEDERATE_NAME              | Name of the SuT federate. In the default parameter settings the federate name `A` is used. This setting must match the actual test case parameters.  | `A`
| POPULATION                 | Size of the starting population for the HelloWorld Country object.   | `10`
| CYCLES                     | Number if iterations before resigning the federate. The federate iterates every second, so this also determines the lifetime the helloworld federate.    | `1000000`
|===

=== Start the HelloWorld application

Start the application with

 docker-compose up

=== Run a test

Once the IVCT and the SUT are up and running, you are able to run the HelloWorld test cases. In the default deployment of the IVCT there is an entry for the helloworld in the SuT section. Login to the IVCT and navigate to the hw_iosb entry in the SuT section.

In the conformance statement of the hw_iosb you need to provide the local settings designator. This valaue is RTI specific. For the Portico RTI you can leave this empty.

You may then select one of the listed interoperability requirements and press the `Execute TC` button. This will open a new tab in the graphical user interface, showing the status and the output from the running test case. The output will also be collected in log files after running test cases.
