= Testing the Hello World application

To execute a test, a System Under Test as well as additional RTI components are needed. The SUT is expected to include any additional RTI components for executing the tests. The IVCT does not include these.

== Obtain and install RTI components

The additional components are RTI implementation specific. For example, the Pitch RTI requires a Pitch Central RTI Component (Pitch CRC), the VTMaK RTI requires an RTI Exec, whereas Portico requires no additional components at all.

Both Pitch and VTMak provide free versions of their RTI. The additional components can be obtained by requesting a free version of the RTI:

- Pitch pRTI Free: http://pitchtechnologies.com/products/prti
- VTMaK RTI Free: https://www.mak.com/products/link/mak-rti

The free version is sufficient for executing tests. The installation of additional RTI components is out of the scope of this getting started section. The remainder of this section assumes that a Pitch CRC has been installed on a host called `mycrc.com`, listening on the default CRC port `8989`.

== Start the Hello World application

<< Reinhard or John to add ... >

Classpath settings for the RTI needeed?  Is there a BAT file per RTI flavor?

== Run a test

<< Reinhard or John to add ... >

Login to the IVCT and navigate to the SUT page ...

Enter the address of the Pitch CRC in the settine designatot ...

Anything else?

Press `Execute` to start the test.

Results are ...
