= Testing the Hello World application

To execute a test, a System Under Test as well as additional RTI components are needed. The SUT is expected to include any additional RTI components for executing the tests. The IVCT does not include these.

== Obtain and install RTI components

The additional components are RTI implementation specific. For example, the Pitch RTI requires a Pitch Central RTI Component (Pitch CRC), the VTMaK RTI requires an RTI Exec, whereas Portico requires no additional components at all.

Both Pitch and VTMak provide free versions of their RTI. The additional components can be obtained by requesting a free version of the RTI:

- Pitch pRTI Free: http://pitchtechnologies.com/products/prti
- VTMaK RTI Free: https://www.mak.com/products/link/mak-rti

The free version is sufficient for executing tests.

The remainder of this section assumes that the Pitch RTI has been installed on the Docker host file system under the directory `${PITCH_RTI_HOME}`.

== Start the HelloWorld application

The test suite ``TS_HelloWorld`` impements two simple test cases, each testing a interoperability requirement defined in the HelloWorld badge. Along with the test suite implementation, there is also the helloWorld federate. This federate can used as a System under Test against the test suite, and it is a good starting point to explore and understand the IVCT installation.

The HelloWorld federate is a simple Java application, that can be used as a console application under Windows and Linux. The application is also provided as a docker image, which is the recommended way to start with. After installing an RTI, as explained in the chapter above, the docker compose files can be used to start the Hello world application and the RTI.

=== Copy the RTI/HelloWorld composition file to you local environment

First you need to copy the content of the `sut-helloworld` directory to your local Docker environment.

=== Adapt the environment settings

Before starting the composition, check the settings in the provided `.env` file.

=== Environment Variables

In the compose file, there are several enviroment variable settings for the helloworld federate. No changes are needed, as long as the crc configuration in the compose file is not changed.

|===
| Environment Variable Name  | Description | Default if not set

| SETTINGS_DESIGNATOR        | Connection parmeter for the `RTIambassador.connect` method   |no default assumed, this variable must be set to the RTI service. A typical value would be `crcAddress=crc:8989`
| FEDERATE_NAME              | Name of the SuT federate. In the default parameter settings the federate name `A` is used. This setting must match the actual test case parameters.  | `A`
| POPULATION                 | Size of the starting population for the HelloWorld Country object.   | `10`
| CYCLES                     | Number if iterations before resigning the federate. The federate iterates every second, so this also determines the lifetime the helloworld federate.    | `1000000`
|===

=== Start the RTI and the helloworld federate

Two compose files are present, one to start the RTI and the other to start the helloworld federated. Start the composition.

=== Run a test

Once the IVCT and the SUT are up and running, you are able to run test cases. In the default deployment of the IVCT there is an entry for the helloworld in the SuT section. Login to the IVCTools and navigate to the hw_iosb entry in the SuT section.

In the conformance statement of the hw_iosb, you need to change the host name in the settings designator. If your IVCTool composition is running on the same docker host as your sut-helloworld composition, the host name will be `crc`.

You may then select one of the listed interoperability requirements and press the `Execute TC` button. This will open a new tab in the graphical user interface, showing the status and the output from the running test case. The output will also be collected in log files after running test cases.
