= Deploying the IVCT

Assuming a Docker Engine and Docker Compose have been installed, the quickest way to get started with the IVCT is as follows.

== Copy the IVCT composition files to your local environment

In this repository there are IVCT compositions for different HLA-RTI implementations. In this example we use the IVCT composition for the Pitch RTI. We also run the IVCT in `overlay` mode, to be explained later.

Copy the files under the `ivct-pitch/overlay-mode` directory to your local Docker environment. This concerns two files:

* `docker-compose.yml`: a Docker compose file describing the IVCT composition.
* `.env`: environment settings related to the Docker compose file.

== Adapt the environment settings

Open the `.env` file in a text editor and set `IVCT_HOST` to the host where the IVCT will be executing. The `IVCT_UIPORT` value should be fine for your environment, but may be adapted too.

== Start the IVCT

Deploy and start the IVCT using the following command:

 docker-compose up

The IVCT Docker container images will be pulled from the Docker Hub and the IVCT will be deployed.

== Login to the IVCT UI

The final step is logging into the IVCT UI. From a webbrowser, navigate to the web page of the IVCT UI: `http://${IVCT_HOST}:${IVCT_UIPORT}`. Here you have to replace `${IVCT_HOST}` and `${IVCT_UIPORT}` by the values used in the `.env` file. If your browsers run on the same host as the IVCT you can use `http://localhost:${IVCT_UIPORT}`.

Login as user `admin` with password `admin.`

Once you are logged in you can explore the UI, as described in more detail at: <<IVCT-Graphical-User-Interface#,Explore the Grapical User Interface>>

However, for executing a test a System Under Test (SUT) as well as a Pitch CRC is required. This is explained at: <<IVCT-GettingStarted-HelloWorld#,Run a test against the HelloWorld SUT>>
