= Deploying the IVCT

Assuming a Docker Engine and Docker Compose have been installed, the quickest way to get started with the IVCT is as follows.

== Copy the IVCT composition files to your local environment

In the Compositions repository there are IVCT compositions for different HLA-RTI implementations. In this example we use the IVCT composition for the Pitch RTI. We also run the IVCT in `overlay` mode, to be explained later.

Copy the files under the `ivct-pitch/overlay-mode` directory to your local Docker environment. This concerns two files:

* `docker-compose.yml`: a Docker compose file describing the IVCT composition.
* `.env`: environment settings related to the Docker compose file.

== Adapt the environment settings

Open the `.env` file in a text editor and set `IVCT_HOST` to the host where the IVCT will be executing. The `IVCT_UIPORT` value should be fine for your environment, but may be adapted too.

== Start the IVCT

Deploy and start the IVCT using the following command:

 docker-compose up

The IVCT Docker container images will be pulled from the Docker Hub and the IVCT will be deployed.

== Login to the IVCT UI

From a webbrowser, navigate to the web page of the IVCT UI: `http://${IVCT_HOST}:${IVCT_UIPORT}`. Here you have to replace `${IVCT_HOST}` and `${IVCT_UIPORT}` by the values used in the `.env` file. Login as user `admin` with password `admin.`

You can explore the UI, but for executing a test a System Under Test (SUT) as well as a Pitch CRC is required.
