= Deploying the IVCT

Assuming a Docker Engine and Docker Compose have been installed, the quickest way to get started with the IVCT is as follows.

== Install RTI on host file system

Due to license restrictions, the IVCT images for the Pitch and VTMaK RTI do not contain the actual RTI files. These images are so called `skeleton` images and the RTI files need to be mounted from the host file system. Only for the Portico RTI the IVCT image incudes the RTI files.

For the Pitch or VTMaK RTI obtain the RTI files from the vendor and install the RTI on your Docker host file system.

In the examples we assume that the Pitch RTI is installed under the directory `${PITCH_RTI_HOME}` and the VTMaK RTI under the directory `${VTMAK_RTI_HOME}`.

More information on this can be found in the project https://github.com/hlacontainers in the Pitch CRC or VTMaK RTI Executive repository.

== Copy the IVCT composition files to your local environment

In this repository there are IVCT and SUT example compositions for different HLA-RTI implementations. In this example we use the IVCT composition for the Pitch RTI. We also run the IVCT in `bridge` network mode, to be explained later.

Copy the directory `pitch/bridge-network` and its contents to your local Docker environment.

== Adapt the environment settings

Open the `.env` file under the `ivct` directory in a text editor and set `PITCH_RTI_HOME` to the directory under which the RTI is installed on the host file system.
Do the same for the `.env` file under the `sut-helloworld` directory.

The `IVCT_UIPORT` value should be fine for your environment, but may be adapted too.

== Start the IVCT

from the `ivct` directory deploy and start the IVCT using the following command:

 docker-compose up

The IVCT Docker container images will be pulled from the Docker Hub and the IVCT will be deployed.

== Login to the IVCT UI

The final step is logging into the IVCT UI. From a webbrowser, navigate to the web page of the IVCT UI: `http://${IVCT_HOST}:${IVCT_UIPORT}`. Here you have to replace `${IVCT_HOST}` and `${IVCT_UIPORT}` by the values used in the `.env` file. If your browser runs on the same host as the IVCT you can use `http://localhost:${IVCT_UIPORT}`.

Login as user `admin` with password `admin.`

Once you are logged in you can explore the UI, as described in more detail at: <<IVCT-GettingStarted-Graphical-User-Interface#,Explore the Grapical User Interface>>

However, for executing a test a System Under Test (SUT) as well as a Pitch CRC is required. This is explained at: <<IVCT-GettingStarted-HelloWorld#,Run a test against the HelloWorld SUT>>
