= Preserving test results

The results of the tests are stored (by the TC Runner Application) in the RunTime Config data volume. However, when this data volume is removed the test results are gone too.

This topic lists several options to preserve the data in the data volume.

== Use driver options (Linux)

This option makes the RunTime Config data volume persistent using the local volume driver options. To do this, add the `local` volume driver to the `runtime-config` volume as shown in the compose file snippet below.

....

version: '3'
# ==============================================================================
# IVCT composition for the Pitch RTI
# ==============================================================================

services:
...

# ==============================================================================
# Data volumes for IVCT Runtime Config data and Test Suite data
# ==============================================================================
volumes:
  runtime-config:
    driver: local
    driver_opts:
      type: none
      device: ${CONFDIR}
      o: bind
  ts-helloworld:
  ts-hla-encoding-rules:
  ts-hla-cs-verification:
  ts-hla-services:
  ts-hla-object:
  ts-hla-declaration:
....

The driver options is a list of key-value pairs that is passed to the driver for this volume, the `local` driver in this example. The environment variable `CONFDIR` must refer to an existing directory on the `IVCT_HOST`, and must be defined in the `.env` file.

For this option to work make sure that the volume `runtime-config` does not exist yet. Otherwise it won't be created with the provided driver options. I.e. stop all containers that use the volume, and issue the `docker volume prune` to remove any volumes not in use anymore.

The documentation about this topic is quite minimal on the Docker documentation site. However it turns out that only the built-in local driver on Linux accepts the driver options. These options are similar to the Linux mount command, and are actually passed on to that command.

To get to the test log of a particular test suite `<TESTSUITE_NAME>` ran against a SUT named `<SUT_NAME>`, navigate to the following directory on the `IVCT_HOST`:

 cd ${CONFDIR}/IVCTsut/<SUT_NAME>/<TESTSUITE_NAME>/Logs

And to the test reports:

 cd ${CONFDIR}/IVCTsut/<SUT_NAME>/Reports

== Use Docker copy command (Windows and Linux)

The second option uses the `docker cp` command to copy data from the data volume to the `IVCT_HOST`, using one of the containers that has mounted this volume. In this example we use the IVCT GUI container to copy out test logs.

To copy the test logs for a particular test - in this example `RPR-Encoding-2.0` for the SUT named `vrf` - do:

 docker cp overlaymode_gui_1:/root/conf/IVCTsut/vrf/RPR-Encoding-2.0/Logs .

Similar for the test reports:

 docker cp overlaymode_gui_1:/root/conf/IVCTsut/vrf/Reports .

The container name `overlaymode_gui_1` refers to the IVCT GUI container in the `overlay-mode` composition. The container ID and container name can be looked up with the command `docker-compose ps` or `docker ps`.

== References:
https://docs.docker.com/engine/reference/commandline/volume_create
