== IVCT TC Runner Application image

The Test Case (TC) Runner Application executes test cases. The TC Runner Application image is based on a Local RTI Component (LRC) Base image.

The LRC Base image is a minimal image and provides basic functionality to launch an HLA federate application. Several LRC Base images are available for different RTI implementations (Pitch, Mak, Portico) and Linux distributions (Alpine, Debian, CentOS). Each LRC Base image includes a Java JRE and provides several environment variables to control the behavior or some settings of the LRC. The LRC Base image settings are overridden by the settings provided via the Local Settings Designator.

At run-time, Test Case execution results are reported via the Active MQ.

=== Environment Variables

For a full list of parameters, see the link:https://github.com/IVCTool/IVCT_Framework/blob/development/docs/src/2-8-IVCT_Configuration.adoc[IVCT Configuration].

The most relevant ones for the Operator are:

|===
| Environment Variable Name   | Description | Default if not set

| `SETTINGS_DESIGNATOR` | Value to use for the RTI connection string if no value is provided in the SuT conformance statement. | The default is an empty string
| `FEDERATION_NAME`     | Value to use for the federation name if no value is provided in SuT conformance statement.  | `TheWorld`
|===

Besides these environment variables, additional environment variables are inherited from the LRC image. The most relevant ones are shown below.

==== Pitch LRC settings
|===
| Environment variable        | Description | Default if not set

| ``PITCH_LRCADAPTER``        | Applies to direct mode. The network adapter that the LRC should use. | Use IP route to CRC to determine adapter
| ``PITCH_CRCADDRESS``        | CRC address in the format of `<host>:<port>` (direct mode) or `<crc-nickname>@<boost host>:<boost port>` (booster mode). | `crc:8989`
| ``PITCH_ADVERTISE_ADDRESS`` | Applies to direct mode. Use this address to advertise the LRC. The format is ``[<host address>][:[<mintcpport>]-[<maxtcpport>][:[<minudpport>]-[<maxudpport>]]]`` | Mode IP, ``:6000-6999:5000-5999``
|===

If the `SETTINGS_DESIGNATOR` is an empty string then the LRC image default behavior comes into play. That is, the federate application (the TC Runner in this case) will use whatever is set by the LRC image as the address for the CRC. The address is the value of the environment variable `PITCH_CRCADDRESS`.

==== Portico LRC settings
|===
| Environment variable        | Description | Default if not set

| ``PORTICO_LRCADAPTER``      | The network adapter (network interface) that the LRC should use. The name must be an exact match. | RID file default
|===

==== VTMaK LRC settings

|===
| Environment variable        | Description | Default if not set

| ``MAK_LRCADAPTER``          | Network interface address to use for the MaK Forwarder | `0.0.0.0`, i.e. first available non-localhost interface address
| ``MAK_RTIEXECADDRESS``      | RTI Exec address in the format of `<host>:<port>`. | `rtiexec:4000`
|===

If the `SETTINGS_DESIGNATOR` is an empty string then the LRC image default behavior comes into play. That is, the federate application (the TC Runner in this case) will use whatever is set by the LRC image as the address for the RTI Exec. The address is the value of the environment variable `MAK_RTIEXECADDRESS`.
