= Running TS_Helloworld-testsuite-tests against HelloWorld application +

Once the IVCT and the SUT are up and running, you are able to run tests 
of the example testsuite TS_HelloWorld against the sample HelloWorld application.


== Prerequisite

You have cloned and deployed the IVCT- Software as described in:
link:Deploy_the_IVCT_and_start.adoc[]

You have cloned and deployed the HelloWorld SUT as described in:
link:Deploy_the_SUT_example_HelloWorld.adoc[]


== Login to the IVCT UI  to test the installation

The IVCT provides a webinterface based on tomcat. This IVCT GUI can be reached 
with a webbrowser at: `http://${DOCKERHOST}:${IVCT_UIPORT}`. +
(You have to replace `DOCKERHOST` and `IVCT_UIPORT` by the values set in the `.env` file.)

 e.g. http://192.168.1.1:8080

Login as user `admin` with password `admin.`



== Adjust the settings in the GUI for your environment

in the first Step you have to choose the RTI you want to work with: +
In the Menue klick on the little gearwheel in the top right corner. +
Under "TestEngine"  pick the RTI  pi-skeleton  [ok]


Now you need to declare how to reach the "Run-Time-Infrastructure" you are working with: +
 In the navigation frame on the left side with a blue background +
 chose the "System under Test (SuT) View" and activate "hw_iosb"  +
 In the pullDown Menue [SuT] of the top Menu Bar  choose "Edit SuT"  +
 Insert in the field "RTI Connection" for connecting with the Pitch RTI you have started: 

 crcAddress=192.168.1.1:8989   ( adapt to your IP)

== Run example Tests

The SuT view lists the test cases for the HelloWord SuT. +
e.g.:    > hw_iosb |  HelloWorld-2019

Select a test case and press the `Execute TC` button. +
This will open a new tab in the graphical user interface, 
showing the status and the output from the running test case. 
The output will also be collected in log files after running test cases.
#to be rewiewed#





== Further steps

=== More Informations to work with the GUI

Once you are logged in you can explore the UI, 
as described in more detail at: 
link:IVCT-GettingStarted-Graphical-User-Interface.adoc[]  #verify this page#

