---
apiVersion: v1
kind: Service
metadata:
  name: tc-runner-pi-srvc
  #name: tc-runner-pi
  # namespace: bbb-test-namespace
spec:
  type: NodePort
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    # - name: "tcp6000"
    - name: "tcp30600"
      #port: 6000
      port: 30600
      protocol: TCP
      #nodePort: 6000
      nodePort: 30600
      #targetPort: 6000
      targetPort: 30600

    #- name: "udp5000"
    - name: "udp30500"
      #port: 5000
      port: 30500
      protocol: UDP
      #nodePort: 5000
      nodePort: 30500
      #targetPort: 5000
      targetPort: 30500

  #externalIPs:
  #  - 10.56.11.20

  selector:
    app: tc-runner-pi
