---
apiVersion: v1
kind: Service
metadata:
  name: sut-helloworld-pi-srvc
  #name: sut-helloworld-pi
  # namespace: bbb-test-namespace
spec:
  type: NodePort
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    - name: "tcp30610"
      #- name: "tcp6100"
      port: 6100
      #port: 30610
      protocol: TCP
      #nodePort: 6100
      nodePort: 30610
      targetPort: 6100
      #targetPort: 30610

    - name: "udp30510"
      #- name: "udp5100"
      port: 5100
      #port: 30510
      protocol: UDP
      #nodePort: 5100
      nodePort: 30510
      targetPort: 5100
      #targetPort: 30510
  #externalIPs:
  #  - 10.56.11.20

  selector:
    app: sut-helloworld-pi
