---
apiVersion: v1
kind: Service
metadata:
  #name: tc-runner-pi-srvc
  name: tc-runner-pi
  #labels:
  #  app: tc-runner-pi
  # namespace: brf-test-namespace
spec:
  type: NodePort
  ports:
    - name: "6000"
      port: 6000
      protocol: TCP
    - name: "5000"
      port: 5000
      protocol: UDP

  selector:
    app: tc-runner-pi
