---
apiVersion: v1
kind: Service
metadata:
  #name: sut-helloworld-pi-srvc
  name: sut-helloworld-pi
  #labels:
  #  app: sut-helloworld-pi
  # namespace: brf-test-namespace
spec:
  type: NodePort
  ports:
    - name: "6100"
      port: 6100
      protocol: TCP
    - name: "5100"
      port: 5100
      protocol: UDP

  selector:
    app: sut-helloworld-pi
