apiVersion: v1
kind: Service
metadata:
  #name: guisrvc
  name: gui
  labels:
    app: gui
  # namespace: bbb-test-namespace
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
    - name: "gui-port"
      port: 8080
      nodePort: 30333
  selector:
    app: gui
