---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sut-helloworld-pi
  # namespace: bbb-test-namespace
  labels:
    app: sut-helloworld-pi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sut-helloworld-pi
  template:
    metadata:
      labels:
        app: sut-helloworld-pi
    spec:
      containers:
        - name: sut-helloworld-pi
          image: ivct/helloworld:pi-skeleton-2.1.3-SNAPSHOT
          # image: ivct/helloworld:pi-skeleton-2.1.2-SNAPSHOT
          imagePullPolicy: Always
          #command: ["/usr/local/lrc/launch.sh"]
          command: ["/bin/sleep"]
          args: ["30m"]
          #args:
          #  - 30m
          # command:
            # - /bin/sh
            # - /bin/sleep
            # - launch.sh
          env:
          #  - name: ACTIVEMQ_HOST
          #    value: activemq
          #    #value: "10.244.0.77"
          #  - name: ACTIVEMQ_PORT
          #    value: "61616"
          #  - name: IVCT_HOME
          #    value: /root/conf/
          #  - name: IVCT_CONF
          #    value: /root/conf/IVCT.properties

            - name: RTI_HOME_FROM
              value: /root/conf/prti1516e
          #  #- name: LRC_HOME
          #  #  value: /root/conf/prti1516e
          #  - name: RTI_HOME
          #    value: /root/conf/prti1516e

          #  - name: LRC_CLASSPATH
          #    value: '/root/conf/prti1516e/lib/prti1516e.jar:/root/conf/prti1516e/lib/prticore.jar:/root/conf/prti1516e/lib/booster1516.jar'

          #  - name: CLASSPATH
          #    value: '/root/conf/prti1516e/lib/prti1516e.jar:/root/conf/prti1516e/lib/prticore.jar:/root/conf/prti1516e/lib/booster1516.jar'

            - name: LRC_LIBRARYPATH
              value: '/root/conf/prti1516e/lib/gcc41_64:/usr/lib/jvm/java-1.8-openjdk/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/lib/amd64/server:'

            - name: LD_LIBRARYPATH
              value: '/root/conf/prti1516e/lib/gcc41_64:/usr/lib/jvm/java-1.8-openjdk/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/lib/amd64/server:'

          #  - name: PITCH_RTI_HOME
          #    value: /root/conf/prti1516e
          #  #- name: PITCH_RTI_SETTINGS
          #  #  value: /root/conf/prti1516e_settings           ###????
          #  - name: SETTINGS_DESIGNATOR
          #    value: "crcAddress=10.56.11.19:8989"
          #    #value: "192.168.49.1:8989"

            - name: FEDERATE_NAME
              value: A
            - name: POPULATION
              value: "100"
            - name: CYCLES
              value: "1000000"

            - name: DOCKERHOST
              value: 192.168.49.2

            - name: PITCH_ADVERTISE_TCP
              value: "6100"
              #value: "30610"
            - name: PITCH_ADVERTISE_UDP
              value: "5100"
              #value: "30510"

            - name: PITCH_ADVERTISE_ADDRESS
              value: "10.56.11.19:6100:5100"
              #value: "192.168.49.2:30610:30510"
              #value: "192.168.49.2:6100:5100"
            - name: PITCH_ADV_ADDRESS
              value: "10.56.11.19:6100:5100"
              #value: "192.168.49.2:30610:30510"

            # - name: PITCH_LRC_SETTINGS_FILE  # , wird erstellt ?
            #   value: /ursr/local/lrc/settings/sut-helloworld
            - name: LRC_DEBUG
              value: "true"

          envFrom:
            - configMapRef:
                name: ivct-config
                       
          ports:
            - name: pi-adv-tcp
              containerPort: 6100
              #containerPort: 30610
              protocol: TCP
            - name: pi-adv-udp
              containerPort: 5100
              #containerPort: 30510
              protocol: UDP

          volumeMounts:
            - mountPath: /root/conf
              name: vol0
      restartPolicy: Always
      volumes:
        - name: vol0
          persistentVolumeClaim:
            claimName: nfs-pv-claim   # ivct-pvc3
